Add files via upload
3 notes for future references:

librosa.core.logamplitude has been removed in v0.6  and has now been replaced by amplitude_to_db. Also the “ref_power” parameter is replaced by “ref”

log_S = librosa.amplitude_to_db(S, ref=np.max)

“TypeError: Object of type 'float32' is not JSON serializable” error during the creation of the .json file can be resolved by writing a serializer and adding “cls=MyEncoder” parameter to json.dump.

json.dump(data, outfile, cls=MyEncoder) 

class MyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(MyEncoder, self).default(obj)


ParameterError: when mode='interp', width=9 cannot exceed data.shape[axis]=n

mode='nearest' can be added to alter the default ‘interp’ to avoid this. This seem to occur in longer audio files.